defaults:
  - override hydra/launcher: submitit_slurm

# command line arguments
train_args:
  device: cuda
  batch_size: 64
  lr: 0.0008
  vocab_size: 32000
  dataset: openwebtext
  checkpoint_every: 10000
  valid_every: 200
  log_every: 200
  n_tokens: 1876800000
  ablation: weight_tying
  num_layers: 6
  d_model: 1024
  d_ff_ratio: 4 
  seq_len: 768
  precision: high
  context_length: 768
  dtype: torch.float32
  amp: True
  weight_decay: 0.2
  run_name: final

# submitit settings
hydra:
  launcher:
    partition: a1-batch
    qos: a1-batch-qos
    timeout_min: 90
    gpus_per_node: 1
    cpus_per_task: 8
    max_num_timeout: 0
    array_parallelism: 10
  
  sweep:
    dir: multirun/leaderboard_90
    subdir: ${hydra.job.override_dirname}
  
  sweeper:
    params:
      train_args.precision: medium
      train_args.dtype: torch.float32
