defaults:
  - override hydra/launcher: submitit_slurm

# command line arguments
train_args:
  device: cuda
  batch_size: 128
  lr: 0.0001
  vocab_size: 32000
  dataset: openwebtext
  checkpoint_every: 5000
  valid_every: 100
  n_tokens: 1276800000
  ablation: weight_tying
  num_layers: 4
  d_model: 512
  d_ff_ratio: 4 
  seq_len: 512
  precision: high
  context_length: 512
  dtype: torch.float32
  weight_decay: 0.01

# submitit settings
hydra:
  launcher:
    partition: a1-batch
    qos: a1-batch-qos
    timeout_min: 90
    gpus_per_node: 1
    cpus_per_task: 8
    max_num_timeout: 0
    array_parallelism: 10
  
  sweep:
    dir: multirun/leaderboard_90
    subdir: ${hydra.job.override_dirname}
  
  sweeper:
    params:
      train_args.lr: 0.0008,0.0015
      train_args.seq_len: 512
      train_args.num_layers: 6
      train_args.d_model: 1024
      train_args.batch_size: 64
      train_args.precision: medium
      train_args.dtype: torch.bfloat16
      train_args.weight_decay: 0.1
