defaults:
  - override hydra/launcher: submitit_slurm

# command line arguments
train_args:
  lr: 0.005
  batch_size: 128
  device: cuda
  ablation: None

# submitit settings
hydra:
  launcher:
    partition: a1-batch
    qos: a1-batch-qos
    timeout_min: 120
    gpus_per_node: 1
    cpus_per_task: 8
    max_num_timeout: 0
    array_parallelism: 16

  sweeper:
    params:
      train_args.lr: 0.001, 0.005
      train_args.ablation: no_layernorm
        #, postnorm, nope, silu
